apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: neuralops
  labels:
    app: user-service
    app.kubernetes.io/part-of: neuralops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8085"
    spec:
      containers:
        - name: user-service
          image: neuralops/user-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: neuralops-config
            - secretRef:
                name: neuralops-secrets
          env:
            - name: SERVER_PORT
              value: "8085"
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "1"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: neuralops
spec:
  selector:
    app: user-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
